/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppPermisosRouteImport } from './routes/_app.permisos'
import { Route as AppModulosRouteImport } from './routes/_app.modulos'
import { Route as AppEventosRouteImport } from './routes/_app.eventos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComponentesRouteImport } from './routes/_app.componentes'
import { Route as AppColegiosRouteImport } from './routes/_app.colegios'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPermisosRoute = AppPermisosRouteImport.update({
  id: '/permisos',
  path: '/permisos',
  getParentRoute: () => AppRoute,
} as any)
const AppModulosRoute = AppModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentesRoute = AppComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => AppRoute,
} as any)
const AppColegiosRoute = AppColegiosRouteImport.update({
  id: '/colegios',
  path: '/colegios',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colegios': typeof AppColegiosRoute
  '/componentes': typeof AppComponentesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/modulos': typeof AppModulosRoute
  '/permisos': typeof AppPermisosRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colegios': typeof AppColegiosRoute
  '/componentes': typeof AppComponentesRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/modulos': typeof AppModulosRoute
  '/permisos': typeof AppPermisosRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/colegios': typeof AppColegiosRoute
  '/_app/componentes': typeof AppComponentesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/modulos': typeof AppModulosRoute
  '/_app/permisos': typeof AppPermisosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colegios'
    | '/componentes'
    | '/dashboard'
    | '/eventos'
    | '/modulos'
    | '/permisos'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colegios'
    | '/componentes'
    | '/dashboard'
    | '/eventos'
    | '/modulos'
    | '/permisos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/colegios'
    | '/_app/componentes'
    | '/_app/dashboard'
    | '/_app/eventos'
    | '/_app/modulos'
    | '/_app/permisos'
    | '/_app/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permisos': {
      id: '/_app/permisos'
      path: '/permisos'
      fullPath: '/permisos'
      preLoaderRoute: typeof AppPermisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modulos': {
      id: '/_app/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof AppModulosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/componentes': {
      id: '/_app/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof AppComponentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colegios': {
      id: '/_app/colegios'
      path: '/colegios'
      fullPath: '/colegios'
      preLoaderRoute: typeof AppColegiosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppColegiosRoute: typeof AppColegiosRoute
  AppComponentesRoute: typeof AppComponentesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventosRoute: typeof AppEventosRoute
  AppModulosRoute: typeof AppModulosRoute
  AppPermisosRoute: typeof AppPermisosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppColegiosRoute: AppColegiosRoute,
  AppComponentesRoute: AppComponentesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventosRoute: AppEventosRoute,
  AppModulosRoute: AppModulosRoute,
  AppPermisosRoute: AppPermisosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
